version: "3.0"

services:
  mongo:
    image: mongo
    container_name: entrega16
    ports:
      - 27017:27017
    volumes:
      - entrega16:/data/configdb
      - entrega16:/data/db
    #restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  entrega16: {}
